### ISSUE TITLE
Module Request: Extron SMP 111

### ISSUE THREAD

**Issue by Veehxia** [bitfocus/companion-module-extron-smp111#1]
Hello, I'd like to request a module for controlling an [Extron SMP 111](https://www.extron.com/product/smp111)
It is a multimedia streaming encoder, I'd love to have buttons on my stream deck to start / stop livestreaming and recording.
Would be even better to have like a "REC" and "LIVE" buttons that switch colors when operating, for example a red "REC" button that turns green once pressed and the recording has started (same for the "LIVE" one)
It can be controlled using telnet / ssh and serial, but I'd prefer using telnet or ssh.
I can provide all the additional informations needed, like commands to send and what the encoder answers (everything can be found in the [user manual ](https://www.extron.com/download/files/userman/smp111_68-2850-01_E.pdf)on the website)
Thank you.

**Comment by EventReplay** [comment]
@josephdadams https://github.com/EventReplay/companion-module-extron-smp111

**Comment by josephdadams** [comment]
@JeffreyDavidsz can you get @EventReplay set up with a repo on the bitfocus account for his new module, companion-module-extron-smp111 ?

**Comment by EventReplay** [comment]
Extron Website has latest firmware 1.03.0014 also 1.02.0006 available for download.

Yes E1RTMP is stream status request, I wanted to know the exact response in Verbose 3 mode as according to manual response is simply 0 or 1 if Vrb3 is not set and would be no good as a polling response!

So in Vrb3 mode you get a response of "RtmpE11" or "RtmpE10"?

I was really trying to avoid polling every couple of seconds.

**Comment by josephdadams** [comment]
This was originally in the module requests repo and I transferred it here, @EventReplay

**Comment by EventReplay** [comment]
@josephdadams thanks, I've been meaning to revisit this.
It could be updated with some of the additions made to the SMP351, my only issue is I can't do any testing. @Veehxia do you still have ability to test if I make changes?

**Comment by EventReplay** [comment]
@Veehxia I have updated this module, it is available in the latest v2 build.
It now requests status of stream every 5 seconds as per your request. If you could confirm it is working ok that would be great.
I will  close this issue, If you have any problem open a new issue here: https://github.com/bitfocus/companion-module-extron-smp111/issues

Thanks
